name: free_swingers_dating
description: Free Swingers.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  http: ^0.13.3

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  image_picker: ^1.0.8
  video_player: ^2.8.5
  mime: ^1.0.4
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  auto_size_text: ^3.0.0
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/check.png
    - assets/images/facebook.png
    - assets/images/free_swingers.png
    - assets/images/fs_bg.png
    - assets/images/instagram.png
    - assets/images/padlock.png
    - assets/images/twitter.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
    - family: Mate
      fonts:
        - asset: assets/fonts/Mate-Regular.ttf
        - asset: assets/fonts/Mate-Italic.ttf
